version: "3.10"

services:
  app:
    build: ./docker/app
    volumes:
      - ./laravel:/app
    ports:
      - "9000:9000"
    working_dir: /app

  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/app
    depends_on:
      - app

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data: